server:
  port: 8003
  servlet:
    context-path: /data_base-app
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5433/tdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres